version: "3.9"
services:
  subscription-manager-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  subscription-manager-frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://your_ip_address:5000
    ports:
      - "3000:3000"
    depends_on:
      - subscription-manager-backend
